version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  versioning-strategy: increase
  ignore:
  - dependency-name: codemaker
    versions:
    - ">= 0"
  - dependency-name: "@jsii/*"
    versions:
    - ">= 0"
  - dependency-name: jsii*
    versions:
    - ">= 0"
  - dependency-name: "@types/node"
    versions:
    - ">=11.0.0-0"
  - dependency-name: aws-sdk
    versions:
    - 2.834.0
    - 2.835.0
    - 2.836.0
    - 2.837.0
    - 2.838.0
    - 2.839.0
    - 2.840.0
    - 2.841.0
    - 2.842.0
    - 2.843.0
    - 2.844.0
    - 2.845.0
    - 2.846.0
    - 2.847.0
    - 2.848.0
    - 2.849.0
    - 2.850.0
    - 2.851.0
    - 2.852.0
    - 2.853.0
    - 2.854.0
    - 2.855.0
    - 2.856.0
    - 2.857.0
    - 2.858.0
    - 2.859.0
    - 2.861.0
    - 2.862.0
    - 2.863.0
    - 2.864.0
    - 2.865.0
    - 2.866.0
    - 2.867.0
    - 2.868.0
    - 2.869.0
    - 2.870.0
    - 2.871.0
    - 2.872.0
    - 2.873.0
    - 2.874.0
    - 2.875.0
    - 2.876.0
    - 2.877.0
    - 2.878.0
    - 2.879.0
    - 2.880.0
    - 2.881.0
    - 2.882.0
    - 2.883.0
    - 2.884.0
    - 2.885.0
    - 2.886.0
    - 2.887.0
    - 2.889.0
    - 2.890.0
    - 2.891.0
    - 2.892.0
    - 2.893.0
    - 2.894.0
    - 2.895.0
  - dependency-name: esbuild
    versions:
    - 0.10.0
    - 0.10.1
    - 0.10.2
    - 0.11.0
    - 0.11.1
    - 0.11.10
    - 0.11.11
    - 0.11.12
    - 0.11.13
    - 0.11.14
    - 0.11.15
    - 0.11.2
    - 0.11.3
    - 0.11.4
    - 0.11.5
    - 0.11.6
    - 0.11.7
    - 0.11.8
    - 0.11.9
    - 0.8.36
    - 0.8.37
    - 0.8.38
    - 0.8.39
    - 0.8.40
    - 0.8.41
    - 0.8.42
    - 0.8.43
    - 0.8.44
    - 0.8.45
    - 0.8.46
    - 0.8.47
    - 0.8.48
    - 0.8.49
    - 0.8.50
    - 0.8.51
    - 0.8.52
    - 0.8.53
    - 0.8.54
    - 0.8.55
    - 0.8.56
    - 0.8.57
    - 0.9.0
    - 0.9.1
    - 0.9.2
    - 0.9.3
    - 0.9.4
    - 0.9.5
    - 0.9.6
    - 0.9.7
  - dependency-name: table
    versions:
    - 6.0.7
    - 6.0.8
    - 6.0.9
    - 6.1.0
    - 6.3.0
    - 6.3.2
    - 6.3.3
    - 6.3.4
    - 6.5.0
    - 6.5.1
  - dependency-name: constructs
    versions:
    - 3.3.36
    - 3.3.37
    - 3.3.41
    - 3.3.43
    - 3.3.44
    - 3.3.45
    - 3.3.47
    - 3.3.48
    - 3.3.49
    - 3.3.50
    - 3.3.53
    - 3.3.54
    - 3.3.55
    - 3.3.58
    - 3.3.59
    - 3.3.61
    - 3.3.62
    - 3.3.63
    - 3.3.64
    - 3.3.65
    - 3.3.66
    - 3.3.67
    - 3.3.68
    - 3.3.70
    - 3.3.71
    - 3.3.72
    - 3.3.74
  - dependency-name: "@types/node"
    versions:
    - 10.17.51
    - 10.17.52
    - 10.17.53
    - 10.17.54
    - 10.17.55
    - 10.17.56
    - 10.17.57
    - 10.17.58
  - dependency-name: "@types/eslint"
    versions:
    - 7.2.6
    - 7.2.7
    - 7.2.8
    - 7.2.9
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@types/aws-lambda"
    versions:
    - 8.10.71
    - 8.10.72
    - 8.10.73
    - 8.10.74
    - 8.10.75
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.0
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.0
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@types/fs-extra"
    versions:
    - 9.0.10
    - 9.0.6
    - 9.0.7
    - 9.0.8
    - 9.0.9
  - dependency-name: "@octokit/rest"
    versions:
    - 18.0.15
    - 18.1.0
    - 18.1.1
    - 18.2.0
    - 18.2.1
    - 18.3.0
    - 18.3.1
    - 18.3.2
    - 18.3.3
    - 18.3.4
    - 18.3.5
    - 18.4.0
    - 18.5.0
    - 18.5.1
    - 18.5.2
  - dependency-name: sinon
    versions:
    - 10.0.0
    - 9.2.4
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: ts-jest
    versions:
    - 26.5.0
    - 26.5.1
    - 26.5.2
    - 26.5.3
    - 26.5.4
  - dependency-name: yaml
    versions:
    - 1.10.1
  - dependency-name: "@types/sinon"
    versions:
    - 9.0.10
    - 9.0.11
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: nock
    versions:
    - 13.0.10
    - 13.0.6
    - 13.0.7
    - 13.0.8
    - 13.0.9
  - dependency-name: string-width
    versions:
    - 4.2.1
    - 4.2.2
  - dependency-name: standard-version
    versions:
    - 9.1.0
    - 9.1.1
  - dependency-name: fast-check
    versions:
    - 2.12.0
    - 2.12.1
    - 2.12.2
    - 2.13.0
  - dependency-name: typescript-json-schema
    versions:
    - 0.48.0
    - 0.49.0
  - dependency-name: graceful-fs
    versions:
    - 4.2.5
  - dependency-name: ts-mock-imports
    versions:
    - 1.3.3
  - dependency-name: delay
    versions:
    - 4.4.1
  - dependency-name: archiver
    versions:
    - 5.2.0
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  - dependency-name: semver
    versions:
    - 7.3.4
  - dependency-name: "@types/table"
    versions:
    - 6.0.0
